### ISSUE TITLE
GPS issue in DarkMoon 004.1

### ISSUE THREAD

**Issue by ashisiniter** [DD3Boh/android_kernel_zuk_msm8996#1]
Hi,

I am new to this. Pardon me for any mistake. I have installed DM in z2 plus. But, the GPS is offset and not accurate at all. 200m offset it was showing after which I did updated via an AGPS app. Please fix it. Its issue of kernel as before this one it was working fine.

**Comment by DD3Boh** [comment]
Okay, I will look through it, afaik the noog-caf branch doesn't have this problem and I'm rebasing the darkmoon on top of it so should work good in the next release, I will make several tests about it before releasing the next version

**Comment by DD3Boh** [comment]
Branch completely changed, issue closed.
