### ISSUE TITLE
Speaker does not work.

### ISSUE THREAD

**Issue by huanmingcn** [DD3Boh/android_kernel_zuk_msm8996#3]
When I change z2_row'kernel to your repository, the speaker does not work, others regular work.

**Comment by DD3Boh** [comment]
I haven't got the z2_row, so I can't specifically test it and I don't exactly know where the problem could be, but I need:
Dmesg
Know which branch you're using

**Comment by huanmingcn** [comment]
All brunch except oreo, if I have time I will sent Dmesg to you.

**Comment by huanmingcn** [comment]
I didn't test Oreo.

**Comment by DD3Boh** [comment]
I basically need to know if you tested the staging/Oops-Kernel branch, because that's the oreo one that should work even with the z2_row, the darkmoon isn't supposed to.

**Comment by huanmingcn** [comment]
![image](https://user-images.githubusercontent.com/13083353/30529095-63a88482-9c6c-11e7-8338-f0af71c22db8.png)

That's all I have tested

**Comment by huanmingcn** [comment]
[message.txt](https://github.com/DD3Boh/android_kernel_zuk_msm8996/files/1310482/message.txt)

**Comment by huanmingcn** [comment]
That is the Dmesg file, my brunch is the staging-noog-caf.

**Comment by DD3Boh** [comment]
You need to try on the branch staging/Oops-Kernel because that's the one supposed to work with the z2_row and has even its defconfig, otherwise I will define this issue a "wontfix", because on noog-caf branch and other nougat branch it isn't supposed to work

**Comment by huanmingcn** [comment]
What does the meaning of Oops? Whether it could work properly in the N?

**Comment by DD3Boh** [comment]
I chose Oops because I didn't find any other better name starting with O lol
and it is like the "next" Noog-CAF, so it's noogcaf but more updated.

**Comment by huanmingcn** [comment]
OK! I will test it tonight.

**Comment by huanmingcn** [comment]
Hey, I just tested it, I'm sorry that the brunch of Oops have the same problem, the microphone and telephont work well, here is the dmesg.
[msg.txt](https://github.com/DD3Boh/android_kernel_zuk_msm8996/files/1310862/msg.txt)

**Comment by huanmingcn** [comment]
E.....I just compiled the boot.img, I have't compile the others, because when I use other kernel the speaker work well, but the performance is worst.

**Comment by huanmingcn** [comment]
OK, I have compiled all, but it also didn't work.

**Comment by huanmingcn** [comment]
And, at the brunch of Oops, the performance of f2fs is worst, all categories are worse. I tried transform the data canche and system, I got the same result.

**Comment by huanmingcn** [comment]
Did you give up z2_row?

**Comment by DD3Boh** [comment]
No, Oreo exists and we're working on it basically now
and anyway the z2_row isn't my priority, I will just try to fix it if possible, but I actually work for the z2_plus.

**Comment by hyman-lee** [comment]
Does the z2 boot up with Oreo ?
