### ISSUE TITLE
Can't record voice with headset

### ISSUE THREAD

**Issue by 508279079** [DD3Boh/android_kernel_zuk_msm8996#5]
Make a call with headset and the other side can't hear my voice. Can't record voice with headset.

**Comment by dmd79** [comment]
No issue here.. please provide a log

**Comment by 508279079** [comment]
This issue happen on LineageOS15, PixelExperience, AICP, AEX. You can use this voice recorder to test. https://play.google.com/store/apps/details?id=com.sonymobile.androidapp.audiorecorder
![screenshot_20180214-082426](https://user-images.githubusercontent.com/15182238/36183099-c3e13b12-1167-11e8-8ae0-41d9c8ae8931.png)

Here is the recording. 
[Recording-2018-02-14 08-29-07.wav.zip](https://github.com/DD3Boh/android_kernel_zuk_msm8996/files/1722297/Recording-2018-02-14.08-29-07.wav.zip)

Sorry. I don't know how to catch a log. Can you tell me?

**Comment by faizauthar12** [comment]
use matlog or any other logcat tools...

**Comment by 508279079** [comment]
Here's the log.
[2018-02-14-10-15-29.txt](https://github.com/DD3Boh/android_kernel_zuk_msm8996/files/1722397/2018-02-14-10-15-29.txt)

**Comment by 508279079** [comment]
I found this issue on ZUI3.5, too.I may be not the issue of the kernel.

**Comment by YaroST12** [comment]
2 commits suggested for a test.
https://github.com/YaroST12/Z2_PLUS_Kernel_EAS/commit/ffbffb2a79b4029ecbbc8880fdd9d5cc70b5e115
https://github.com/YaroST12/Z2_PLUS_Kernel_EAS/commit/24e1b8d86d805e6f629acc1a22a750074e789679
EDIT: seems to recoed fine.

**Comment by 508279079** [comment]
I found this issue on ZUI3.5, too. It may not the issue of the kernel.

**Comment by 508279079** [comment]
This issue only happens at using Earpods. Recorder work well on every Nougat ROM with Earpods.

**Comment by 508279079** [comment]
Press the button in the middle of the line after inserting the headset and the issue disappeared. However. Press the middle button continuously after recording. The headset icon of status bar will change indefinite.

**Comment by 508279079** [comment]
The headset that support Android mobile phone can not increase the volume by drive-by-wire.

**Comment by DD3Boh** [comment]
Closing the issue:
Works fine on lineage 16.0 with Xiaomi Mi Hybrid Pro HD
Tested with the app linked above
