### ISSUE TITLE
USB Tethering is not working

### ISSUE THREAD

**Issue by olivbau** [DD3Boh/android_kernel_zuk_msm8996#7]
USB Tethering is not working
When i click on USB tethering switch nothing happens

Video to reproduce
[video.zip](https://github.com/DD3Boh/android_kernel_zuk_msm8996/files/1822602/video.zip)

Android 8.1.0
Aosp 5.3

**Comment by justks** [comment]
@olivbau It's a known bug right now.
It broke with initial treble support earlier it was working.
PS: It is not a kernel issue lol

**Comment by DD3Boh** [comment]
1. It works on Lineage 16.0 Pie with partial treble enabled
2. It's not a Kernel issue
